# ui.py

import streamlit as st
import requests

# Page configuration
st.set_page_config(page_title="Ask-Your-Docs", layout="wide")

# Retrieve the API base URL from Streamlit secrets
API_URL = "http://localhost:8000" # Default to localhost if not set
#st.secrets["API_URL"]

st.title("📚 Ask-Your-Docs")
st.write(
    """
    Ask natural-language questions over your own document corpus.
    The answers are generated by combining semantic retrieval with a powerful LLM.
    """
)

# Input field for the user query
query = st.text_input("Enter your question here:")

if st.button("Ask"):
    if not query:
        st.warning("Please enter a question.")
    else:
        with st.spinner("Retrieving and generating answer..."):
            try:
                response = requests.post(
                    f"{API_URL}/query",
                    json={"question": query},
                    timeout=30
                )
                response.raise_for_status()
                data = response.json()
                
                # Display the generated answer
                st.subheader("📝 Answer")
                st.write(data.get("answer", "No answer returned."))
                
                # Display the source passages
                st.subheader("📖 Sources")
                sources = data.get("sources", [])
                if sources:
                    for i, src in enumerate(sources, 1):
                        st.markdown(f"**Source {i}:** {src[:500]}…")
                else:
                    st.info("No source passages returned.")
            
            except requests.exceptions.RequestException as e:
                st.error(f"Request failed: {e}")
